version: '3'

services:
  base_app:
    container_name: base_app
    image: baseapp
    restart: unless-stopped
    ports:
    - "3838:3838"
    networks:
    - base_app_net

networks:
  base_app_net:
